### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by powerey** [jfhealthcare/object-CXR#10]
I can't use Baidu Pan(access code : w3m5) to download the data.
![未命名1590998834](https://user-images.githubusercontent.com/64997076/83388993-0486ae00-a422-11ea-9759-07dc51db11a0.png)

**Comment by yil8** [comment]
Yeah it's broken...we'll trying to figure out other ways to host it

**Comment by yil8** [comment]
@powerey the baidu link has been updated, can you try it again?

**Comment by powerey** [comment]
New link is good to use
